
/// <reference types="nexacro" />
/// <reference types="nexacro-compbase" />
/// <reference types="nexacro-comcomp" />
/// <reference types="nexacro-grid" />
/// <reference types="nexacro-deviceapi" />

//// <reference path="./Base" />
//// <reference path="./frame" />
//// <reference path="./Test" />
//// <reference path="./libs" />

type Button = nexacro.Button;
type Combo = nexacro.Combo;
type Edit = nexacro.Edit;
type MaskEdit = nexacro.MaskEdit;
type TextArea = nexacro.TextArea;
type Static = nexacro.Static;
type Div = nexacro.Div;
type PopupDiv = nexacro.PopupDiv;
type Radio = nexacro.Radio;
type CheckBox = nexacro.CheckBox;
type ListBox = nexacro.ListBox;
type Grid = nexacro.Grid;
type Spin = nexacro.Spin;
type Menu = nexacro.Menu;
type PopupMenu = nexacro.PopupMenu;
type Tab = nexacro.Tab;
type GroupBox = nexacro.GroupBox;
type Calendar = nexacro.Calendar;
type ImageViewer = nexacro.ImageViewer;
type ProgressBar = nexacro.ProgressBar;
type Plugin = nexacro.Plugin;
type Dataset = nexacro.Dataset;
type WebBrowser = nexacro.WebBrowser;
type DataObject = nexacro.DataObject;
type FileUpload = nexacro.FileUpload;

declare var Button: nexacro.Button;
declare var Combo: nexacro.Combo;
declare var Edit: nexacro.Edit;
declare var MaskEdit: nexacro.MaskEdit;
declare var TextArea: nexacro.TextArea;
declare var Static: nexacro.Static;
declare var Div: nexacro.Div;
declare var PopupDiv: nexacro.PopupDiv;
declare var Radio: nexacro.Radio;
declare var CheckBox: nexacro.CheckBox;
declare var ListBox: nexacro.ListBox;
declare var Grid: nexacro.Grid;
declare var Spin: nexacro.Spin;
declare var Menu: nexacro.Menu;
declare var PopupMenu: nexacro.PopupMenu;
declare var Tab: nexacro.Tab;
declare var GroupBox: nexacro.GroupBox;
declare var Calendar: nexacro.Calendar;
declare var ImageViewer: nexacro.ImageViewer;
declare var ProgressBar: nexacro.ProgressBar;
declare var Plugin: nexacro.Plugin;
declare var Dataset: nexacro.Dataset;
declare var WebBrowser: nexacro.WebBrowser;
declare var DataObject: nexacro.DataObject;
declare var FileUpload: nexacro.FileUpload;

